name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repo (granwyntan/BytePenguin)
      - name: Checkout Source Repository (granwyntan/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          path: temp  # Clone into "temp" folder

      # Set up Git for the destination repo (BytePenguinCode/BytePenguin)
      - name: Configure Git for Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          echo "[LOG] Setting up Git"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      # Add destination repository as remote
      - name: Add Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Adding destination remote repository"
          git remote add destination https://${{ secrets.GH_PAT }}@github.com/BytePenguinCode/BytePenguin.git

      # Stash any uncommitted local changes
      - name: Stash Local Changes (if any)
        run: |
          cd temp
          echo "[LOG] Stashing local changes"
          git stash -u  # Stash all local changes (including untracked files)

      # Pull changes from the destination repository
      - name: Pull changes from Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Pulling changes from destination repository"
          git fetch destination  # Fetch latest changes from destination repo
          git pull --no-rebase destination main  # Use merge strategy to pull changes from destination repo

      # Copy files from the source repository to the temp folder
      - name: Copy Files from Source Repo to Temp Directory
        run: |
          echo "[LOG] Copying files from granwyntan/BytePenguin"
          cp -r * ../temp  # Copy all files from source to temp directory

      # Debug Git Status
      - name: Debug Git Status
        run: |
          cd temp
          echo "[LOG] Checking Git Status"
          git status
          git diff --stat

      # Restore stashed changes, if any, after the pull
      - name: Restore Stashed Changes (if any)
        run: |
          cd temp
          echo "[LOG] Restoring stashed changes"
          git stash pop || echo "[LOG] No changes to restore"

      # Stage, commit, and push changes to the destination repository (BytePenguinCode/BytePenguin)
      - name: Sync and Push Changes to Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Staging new files"
          git add .
          
          # Check if there are any changes before committing
          if git diff --staged --quiet; then
            echo "[LOG] No changes to commit."
          else
            echo "[LOG] Committing new files"
            git commit -m "Sync new files from granwyntan/BytePenguin"
            echo "[LOG] Pushing changes to BytePenguinCode/BytePenguin"

            # Attempt to push to the destination repo
            git push destination main || { echo "[ERROR] Push failed!"; exit 1; }
          fi
