name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository (granwyntan/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          path: temp  # Clone into "temp" folder

      - name: Verify Cloned Files
        run: |
          echo "[LOG] Listing cloned files from granwyntan/BytePenguin"
          ls -lah temp

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Add Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          git remote add destination https://${{ secrets.GH_PAT }}@github.com/BytePenguinCode/BytePenguin.git
          git fetch destination main || echo "[LOG] No existing main branch"

      - name: Debug Git Status
        run: |
          cd temp
          echo "[LOG] Checking Git Status"
          git status
          git diff --stat

      - name: Sync and Push Changes
        run: |
          cd temp
          echo "[LOG] Staging changes"
          git add .

          # Check if there are any changes before committing
          if git diff --staged --quiet; then
            echo "[LOG] No changes to commit."
          else
            echo "[LOG] Committing changes"
            git commit -m "Sync from granwyntan/BytePenguin"

            echo "[LOG] Pushing changes"
            git push --force destination main
          fi
