name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}

      - name: Clone Destination Repository
        run: |
          echo "[LOG] Cloning Destination Repository"
          git clone https://github.com/BytePenguinCode/BytePenguin.git

      - name: Sync Repository Contents
        run: |
          echo "[LOG] Syncing Files"
          rsync -av --delete --exclude=".git" ./ temp/

      - name: Commit and Push Changes
        run: |
          cd temp

          echo "[LOG] Setting up Git"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          
          echo "[LOG] Verifying Git Remote"
          git remote -v
          
          echo "[LOG] Updating Remote Repository URL"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/BytePenguinCode/BytePenguin.git
          
          echo "[LOG] Staging Changes"
          git add .
          
          # Check if there are any changes before committing
          if git diff --quiet; then
            echo "[LOG] No changes to commit."
          else
            echo "[LOG] Committing Changes"
            git commit -m "EHEHEH"
          
            echo "[LOG] Pushing Changes"
            if git push origin main; then
              echo "[LOG] Push Successful!"
            else
              echo "[ERROR] Push Failed. Check permissions or network."
              exit 1
            fi
          fi
