name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repo (granwyntan/BytePenguin)
      - name: Checkout Source Repository (granwyntan/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          path: temp  # Clone into "temp" folder

      # Set up Git for the destination repo (BytePenguinCode/BytePenguin)
      - name: Configure Git for Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          echo "[LOG] Setting up Git"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      # Add destination repository as remote
      - name: Add Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Adding destination remote repository"
          git remote add destination https://${{ secrets.GH_PAT }}@github.com/BytePenguinCode/BytePenguin.git

      # Stash any uncommitted local changes (if any)
      - name: Stash Local Changes (if any)
        run: |
          cd temp
          echo "[LOG] Stashing local changes"
          git stash -u  # Stash all local changes (including untracked files)

      # Force push source repository's files to the destination repository
      - name: Push changes to Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Pushing changes from source to destination repository"
          
          # Fetch the latest changes from destination repo
          git fetch destination
          
          # Reset to the latest state of the source (granwyntan/BytePenguin)
          git reset --hard HEAD  # Ensure we're in a clean state, aligned with source repository

          # Stage all changes
          git add .
          
          # Commit the changes
          git commit -m "Sync new files from granwyntan/BytePenguin"
          
          # Force push the changes directly to the destination repository
          git push --force destination main || { echo "[ERROR] Push failed!"; exit 1; }

      # Debug Git Status (optional)
      - name: Debug Git Status
        run: |
          cd temp
          echo "[LOG] Checking Git Status"
          git status
