name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 30 minutes
  push:
    branches:
      - main  # Runs on every push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Add Destination Repository as Remote
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add destination https://github.com/BytePenguinCode/BytePenguin.git
          git fetch destination main
          git push --force destination main
        env:
          USERNAME: BytePenguinCode
          TOKEN: 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
