name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the destination repo (BytePenguinCode/BytePenguin)
      - name: Checkout Destination Repository (BytePenguinCode/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "BytePenguinCode/BytePenguin"
          token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          path: destination  # Clone into "destination" folder

      # Set up Git for the destination repo (BytePenguinCode/BytePenguin)
      - name: Configure Git for Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          echo "[LOG] Setting up Git"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      # Add source repository as remote and fetch changes
      - name: Add Source Repository (granwyntan/BytePenguin)
        run: |
          cd destination
          echo "[LOG] Adding source remote repository"
          git remote add source https://${{ secrets.GH_PAT }}@github.com/granwyntan/BytePenguin.git
          echo "[LOG] Fetching changes from source repository"
          git fetch source  # Fetch the latest changes from source repo

      # Clean the destination repo (remove old files)
      - name: Clean Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd destination
          echo "[LOG] Cleaning destination repository"
          git rm -r --cached .  # Remove all files from the git index (without deleting from local)
          git commit -m "Clean the repository before syncing new files"  # Commit the removal of old files

      # Clone the source repository (granwyntan/BytePenguin) into a temporary folder
      - name: Checkout Source Repository (granwyntan/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}
          path: temp  # Clone into a temporary folder

      # Copy files from the source repository into the destination repo directory
      - name: Copy Files from Source Repo to Destination Repo
        run: |
          echo "[LOG] Copying files from granwyntan/BytePenguin"
          cp -r temp/* destination/  # Copy all files from source repo to destination folder

      # Debug Git Status (optional)
      - name: Debug Git Status
        run: |
          cd destination
          echo "[LOG] Checking Git Status"
          git status

      # Stage, commit, and push changes to the destination repository (BytePenguinCode/BytePenguin)
      - name: Sync and Push Changes to Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          cd destination
          echo "[LOG] Staging new files"
          git add .
          
          # Check if there are any changes before committing
          if git diff --staged --quiet; then
            echo "[LOG] No changes detected."
            exit 0
          fi

          echo "[LOG] Committing new files"
          git commit -m "Sync new files from granwyntan/BytePenguin"
          echo "[LOG] Pushing changes to BytePenguinCode/BytePenguin"

          # Push the changes to the destination repository (BytePenguinCode/BytePenguin)
          git push origin main || { echo "[ERROR] Push failed!"; exit 1; }
