name: Sync Repositories

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  push:
    branches:
      - main  # Runs on every push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository (granwyntan/BytePenguin)
        uses: actions/checkout@v4
        with:
          repository: "granwyntan/BytePenguin"
          token: ${{ secrets.GH_PAT }}  # Ensure this secret is set
          path: temp  # Clone into "temp" folder

      - name: Configure Git for Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          echo "[LOG] Setting up Git"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Add Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Adding destination remote repository"
          git remote add destination https://${{ secrets.GH_PAT }}@github.com/BytePenguinCode/BytePenguin.git
          git fetch destination  # Fetch the destination repo

      - name: Clean Destination Repository (BytePenguinCode/BytePenguin)
        run: |
          echo "[LOG] Cleaning BytePenguinCode/BytePenguin repository"
          cd temp
          git rm -r --cached .  # Remove all files from the git index (without deleting from local)
          git commit -m "Clean the repository before syncing new files"  # Commit the removal of old files

      - name: Copy Files from Source Repo to Temp Directory
        run: |
          echo "[LOG] Copying files from granwyntan/BytePenguin"
          cp -r * ../temp  # Copy all files from source to temp directory

      - name: Debug Git Status
        run: |
          cd temp
          echo "[LOG] Checking Git Status"
          git status
          git diff --stat

      - name: Reset Remote Repository (Force Push)
        run: |
          cd temp
          echo "[LOG] Resetting to destination repository's main branch"
          
          # Reset to destination's main branch
          git fetch destination main
          git reset --hard destination/main
          git clean -fd  # Clean untracked files

      - name: Sync and Push Changes to Destination Repo (BytePenguinCode/BytePenguin)
        run: |
          cd temp
          echo "[LOG] Staging new files"
          git add .
          
          # Check if there are any changes before committing
          if git diff --staged --quiet; then
            echo "[LOG] No changes to commit."
          else
            echo "[LOG] Committing new files"
            git commit -m "Sync new files from granwyntan/BytePenguin"
            echo "[LOG] Pushing changes to BytePenguinCode/BytePenguin"
            git push --force destination main || { echo "[ERROR] Push failed!"; exit 1; }
          fi
